const GET_CODE_REQUEST = 'features/Editor/GET_CODE_REQUEST'
const GET_CODE_SUCCESS = 'features/Editor/GET_CODE_SUCCESS'
const GET_CODE_FAILURE = 'features/Editor/GET_CODE_FAILURE'

const POST_CODE_REQUEST = 'features/Editor/POST_CODE_REQUEST'
const POST_CODE_SUCCESS = 'features/Editor/POST_CODE_SUCCESS'
const POST_CODE_FAILURE = 'features/Editor/POST_CODE_FAILURE'

const CHANGE_CODE = 'features/Editor/CHANGE_CODE'
const KEY_PRESSED = 'features/Editor/KEY_PRESSED'

const ZOOM_IN_REQUEST = 'features/Editor/ZOOM_IN_REQUEST'
const ZOOM_OUT_REQUEST = 'features/Editor/ZOOM_OUT_REQUEST'

export default {
  GET_CODE_REQUEST,
  GET_CODE_SUCCESS,
  GET_CODE_FAILURE,
  POST_CODE_REQUEST,
  POST_CODE_SUCCESS,
  POST_CODE_FAILURE,
  CHANGE_CODE,
  KEY_PRESSED,
  ZOOM_IN_REQUEST,
  ZOOM_OUT_REQUEST
}
